# Generated by Django 5.0.14 on 2025-06-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterlinkData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_cell', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('operator', models.CharField(max_length=100)),
                ('part_model', models.CharField(max_length=100)),
                ('part_status', models.CharField(max_length=100)),
                ('comp_sr_no', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=100)),
                ('machine', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'app_interlinkdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('primary_contact_person', models.CharField(max_length=255)),
                ('secondary_contact_person', models.CharField(max_length=255)),
                ('primary_email', models.EmailField(max_length=254)),
                ('secondary_email', models.EmailField(max_length=254)),
                ('primary_phone_no', models.CharField(max_length=15)),
                ('secondary_phone_no', models.CharField(max_length=15)),
                ('primary_dept', models.CharField(max_length=255)),
                ('secondary_dept', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_password', models.CharField(max_length=255)),
                ('smtp_server', models.CharField(max_length=255)),
                ('smtp_port', models.IntegerField()),
            ],
        ),
    ]
