# Generated by Django 5.0.14 on 2025-06-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_interlinkdata_customer_mailsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftRedirectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('redirected', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('shift_name', 'date')},
            },
        ),
    ]
