# Generated by Django 5.0.14 on 2025-06-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_shiftredirectlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='paratabledata',
            name='single_double',
            field=models.BooleanField(default=False),
        ),
    ]
