# Generated by Django 5.0.14 on 2025-07-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_paratabledata_single_double'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.PositiveIntegerField()),
                ('minute', models.PositiveIntegerField()),
            ],
        ),
    ]
