# Generated by Django 5.0.14 on 2025-07-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_masterinterval'),
    ]

    operations = [
        migrations.AddField(
            model_name='paratabledata',
            name='fixed_channel',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
