# Generated by Django 5.0.14 on 2025-07-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_master_data_channel_fixed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableClearFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clear_table', models.BooleanField(default=False)),
            ],
        ),
    ]
