# Generated by Django 5.0.14 on 2025-07-28 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_tableclearflag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interlinkdata',
            options={},
        ),
    ]
