# Generated by Django 5.0.14 on 2025-07-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_interlinkdata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interlinkdata',
            options={'managed': False},
        ),
    ]
