# Generated by Django 5.0.14 on 2025-07-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_interlinkdata_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterlinkData',
        ),
    ]
