# Generated by Django 5.0.14 on 2025-07-28 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_interlinkdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterlinkData',
        ),
    ]
