# Generated by Django 5.0.14 on 2025-07-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_interlinkdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterlinkData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Time', models.DateTimeField()),
                ('PartModel', models.CharField(max_length=50)),
                ('CompSrNo', models.CharField(max_length=150)),
                ('CompResultStatus', models.CharField(max_length=50)),
            ],
        ),
    ]
